add logic for users and items
c0m14/java-shareit pull request #1
Opened 2023-06-09 21:02 UTC by c0m14

2023-06-10 18:15 UTC, ohelly requested changes
Привет! Отличная работа, все работает корректно. Оставил несколько рекомендаций, на которые стоит обратить внимание. Их выполнение необязательно

2023-06-10 18:15 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +
Отсутствует поле request

2023-06-10 18:15 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
Рекомендация: маппер можно вынести в отдельный пакет mapper

2023-06-10 18:15 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (requestedUser.isEmpty()) {
Рекомендация: Данное действие можно написать более лакониично, исполья Optional
![image](https://github.com/c0m14/java-shareit/assets/51891976/6dc48d05-9d18-47c0-954c-bf8b5aa03a9a)

2023-06-10 18:15 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +        if (requestedUser == null) {
Рекомендация: У опционала есть метод ofNullable
![image](https://github.com/c0m14/java-shareit/assets/51891976/07d821c8-215b-439d-b47b-f59a1a73792d)

2023-06-10 18:15 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +        Optional<String> duplicateEmail = repository.values().stream()
Рекомендация: У стримов есть метод anyMatch
![image](https://github.com/c0m14/java-shareit/assets/51891976/b33916a6-5403-494a-a599-c28ee4316abe)

2023-06-11 09:15 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +
Спасибо, думал пока не добавлять до добавления функциональности запросов, но пропишу сразу, чтобы не забыть :)

2023-06-11 09:16 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
Спасибо! :)

2023-06-11 09:25 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (requestedUser.isEmpty()) {
Спасибо! что-то я затупил в юзерах))

2023-06-11 09:39 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/user/repository/InMemoryUserRepository.java
> +        Optional<String> duplicateEmail = repository.values().stream()
Спасибо!

2023-06-11 17:08 UTC, ohelly approved these changes
Привет! Все супер, отличная работа. Можно двигаться дальше!

2023-06-13 08:11 UTC, merged