feat: add bookings
c0m14/java-shareit pull request #2
Opened 2023-06-25 15:42 UTC by c0m14

2023-06-26 16:31 UTC, ohelly requested changes
Привет! Видно, что проделана большая работа. Приложение в целом работает корректно, но есть несколько моментов, которые необходимо исправить. Также оставил ряд рекомендаций, на которые стоит обратить внимание.
В случае возникновения вопросов можно смело обращаться ко мне в пачке

2023-06-26 16:31 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Необходимо исправить: Настоятельно не рекомендуется использовать аннотацию ``@Data`` над сущностями
Тут хорошее объяснение
https://habr.com/ru/companies/haulmont/articles/564682/

Также относится ко всем остальным сущностям

2023-06-26 16:31 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @OneToOne(fetch = FetchType.LAZY)
Необходимо исправить: Указана неправильная связь между букингом и пользвателем. Пользователь может создать больше одного бронирования, поэтому здесь необходимо исправить на ``@ManyToOne``

2023-06-26 16:31 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToOne(fetch = FetchType.LAZY)
Необходимо исправить: Также указана неверная связь. У одной вещи может быть несколько запросов, из которых потом владелец будет выбирать. Необходимо изменить связь на ``@OneToMany``

2023-06-26 16:31 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (!userWithSameEmailOptional.get().equals(user)) {
Так как необходимо будет удалить аннотации ``@Data`` из сущностей, из-за чего метод equals не будет работать, то нужно будет немного поправить условие и сравнивать по идентификатору:
![image](https://github.com/c0m14/java-shareit/assets/51891976/89a30c09-3a77-4d76-b4cb-8502fd86e46c)

2023-06-26 16:31 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public UserDto add(UserCreateDto userCreateDto) {
Рекомендация: Над всеми методами, в которых происходят запросы в БД, особенно обновление и вставка данных, рекомендуется вешать аннотацию ``@Transactional``. Настально рекомендую ознакомиться с транзакциями, чтобы понимать что это вообще такое, так как про это будут спрашивать на собеседованиях 100%

2023-06-26 16:31 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        log.info("Got request to create booking from user with id {}");
Пропущена переменная в логе
![image](https://github.com/c0m14/java-shareit/assets/51891976/3077637e-94c0-43c6-8dc1-4cb9f580046c)

2023-06-26 16:31 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @OneToOne(fetch = FetchType.LAZY)
Необходимо исправить: Также указана неверная связь. У пользователя может быть несколько комментариев, поэтому связь необходимо поменять на ``@ManyToOne``

2023-06-26 18:51 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
о, спасибо большое!

2023-06-26 18:52 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @OneToOne(fetch = FetchType.LAZY)
Спасибо! да, что-то я затупил тут :(

2023-06-26 18:54 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @OneToOne(fetch = FetchType.LAZY)
Спасибо!

2023-06-26 18:57 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        log.info("Got request to create booking from user with id {}");
ой, спасибо большое!

2023-06-26 18:57 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @OneToOne(fetch = FetchType.LAZY)
Спасибо! что-то я выключил логику почему-то в связях(

2023-06-26 19:03 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public UserDto add(UserCreateDto userCreateDto) {
Спасибо большое! когда делал ручные запросы было прям очевидно обернуть, а тут я что-то не учел

2023-06-26 19:44 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (!userWithSameEmailOptional.get().equals(user)) {
Cпасибо! тут немного еще подрефакторить пришлось - метод findByEmail стал обновлять запись в БД (насколько понял из-за того что передавал туда entity)

2023-06-27 19:17 UTC, ohelly approved these changes
Привет! Все отлично, исправлены все замечания. Работу принимаю, можно двигаться дальше!

2023-06-27 19:17 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Есть разница между ``@OneToMany`` и ``@ManyToOne``. В данном случае нужна именно первая: 1 вещь - несколько запросов

2023-06-27 19:34 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @ManyToOne(fetch = FetchType.LAZY)
ой, спасибо большое! поправлю после merge :)

2023-06-27 19:35 UTC, c0m14 commented
Спасибо большое за советы и замечания! :)

2023-06-27 19:36 UTC, merged