Add item requests
c0m14/java-shareit pull request #3
Opened 2023-07-13 07:11 UTC by c0m14

2023-07-13 19:19 UTC, ohelly requested changes
Привет! В целом отличная работа, все работает корректно. Есть одно небольшое замечание и пара рекомендаций.

2023-07-13 19:19 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/controller/RequestController.java
> +        CreateRequestParams requestParams = new CreateRequestParams(ownerId, requestDto);
Рекомендация: Если данный класс создан только для того, чтобы выводить информацию в лог, то в целом можно удалить и в лог выводить руками оба:
![image](https://github.com/c0m14/java-shareit/assets/51891976/40534b5c-c6b0-4fd5-a66b-c3ae9ddb0d6e)

2023-07-13 19:19 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/mapper/RequestMapper.java
> +                            itemRepository.findAllByRequest_RequestId(itemRequest.getRequestId())
Рекомендация: Для того чтобы не делать тут запросы можно добавить связь на итемы в классе Request ``@OneToMany``

2023-07-13 19:19 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +                        .filter(request -> !Objects.equals(userId, request.getOwner().getId())),
Необходимо исправить: Будет лучше сделать это запросом в бд, например ``findAllByIdNotIn()``

2023-07-14 12:59 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/request/controller/RequestController.java
> +        CreateRequestParams requestParams = new CreateRequestParams(ownerId, requestDto);
Cпасибо! Увидел такую практику в рабочем проекте, показалось избыточным, но подумал, что обычная практика для логирования - убрал везде, где меньше трех параметров

2023-07-14 12:59 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/request/mapper/RequestMapper.java
> +                            itemRepository.findAllByRequest_RequestId(itemRequest.getRequestId())
Спасибо большое, поправил)

2023-07-14 12:59 UTC, c0m14 commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +                        .filter(request -> !Objects.equals(userId, request.getOwner().getId())),
о, спасибо! что-то я забыл совсем про оптимальность сразу при запросе в БД сделать фильтр

2023-07-14 18:35 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, можно двигаться дальше!

2023-07-14 19:56 UTC, merged