feat: separate apps and tests and add docker settings
c0m14/java-shareit pull request #4
Opened 2023-07-18 13:51 UTC by c0m14

Логика приложения разделена на два модуля (вместе с тестами) + добавлены скрипты для развертывания

PS сорри, из-за того, что шаблоны были в другом проекте и делал всю логику там - в этот пришлось перетаскивать полностью классы некоторые и плохо могут читаться изменения)

2023-07-18 20:38 UTC, ohelly requested changes
Привет! Отличная работа, все работет корректно, замечаний нет. Оставил пару рекомендаций - их выполнение на твое усмотрение

2023-07-18 20:38 UTC, ohelly commented on gateway/src/main/java/ru/practicum/shareit/gateway/BaseClient.java
> +public class BaseClient {
Рекомендация: HttpClient можно написать с использованием feign(https://www.baeldung.com/spring-cloud-openfeign)
Или с помощью webClient(зависимость webflux)
С ними придется писать намного меньше кода

2023-07-18 20:38 UTC, ohelly commented on gateway/src/main/java/ru/practicum/shareit/gateway/exception/GateWayErrorHandler.java
> +public class GateWayErrorHandler {
Рекомендация: Также можно добавить обрабочтик всхе остальных ошибок
![image](https://github.com/c0m14/java-shareit/assets/51891976/abf2e910-f572-4a54-8f72-b58f0fb80c14)

2023-07-19 05:43 UTC, c0m14 commented on gateway/src/main/java/ru/practicum/shareit/gateway/BaseClient.java
> +public class BaseClient {
ооо, спасибо большое! как раз себе ставил галочку webClient изучить - отличный повод))

2023-07-21 12:07 UTC, c0m14 commented on gateway/src/main/java/ru/practicum/shareit/gateway/exception/GateWayErrorHandler.java
> +public class GateWayErrorHandler {
Спасибо, добавил :)

2023-07-21 12:10 UTC, c0m14 commented on gateway/src/main/java/ru/practicum/shareit/gateway/BaseClient.java
> +public class BaseClient {
Добавил реализацию :) 
Единственно пришлось в одном месте сделать ручную обработку 400 кода ответа от сервера, именно на этом статусе webclient почему-то возвращает в Postman некорректный ответ, если его вручную не отлавливать и не возвращать (при этом с 409, 404, 500 нет проблем), нагуглить почему так не получилось :(

2023-07-21 19:41 UTC, ohelly commented on gateway/src/main/java/ru/practicum/shareit/gateway/BaseClient.java
> +public class BaseClient {
Тут к сожалению не подскажу, так как с ним не особо много работал, в основном работал с feign

2023-07-21 19:42 UTC, ohelly approved these changes
Привет! Все супер, отличная работа. Можно двигаться дальше!

2023-07-24 08:57 UTC, merged